name: Nightly Build
on:
    # Run everyday at 5:30 UTC
    schedule:
      - cron: '30 5 * * *'
  
jobs:
    make_docker_gui_debug_image:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Setup project environment
          run: make env
        - name: Make the build
          run: |
            make docker-gui-debug
            make docker-save
        - name: Upload the build
          uses: actions/upload-artifact@v4
          with:
            name: docker_gui(debug)
            path: build/docker/bombsquad_gui_debug_docker.tar
    
    make_docker_server_debug_image:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Setup project environment
          run: make env
        - name: Make the build
          run: |
            make docker-server-debug
            make docker-save
        - name: Upload the build
          uses: actions/upload-artifact@v4
          with:
            name: docker_server(debug)
            path: build/docker/bombsquad_server_debug_docker.tar
            
    make_sphinx_docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Setup project environment
          run: make env
        - name: Make the build
          run: make docs-sphinx
        - name: Upload the build
          uses: actions/upload-artifact@v4
          with:
            name: sphinx_html_docs
            path: build/sphinx